Exercise10.1
CzarekOrlikowski/zadanie10.1 pull request #1
Opened 2020-05-12 13:57 UTC by CzarekOrlikowski

2020-05-12 18:19 UTC, pawel-javastart requested changes

2020-05-12 18:19 UTC, pawelkoperjavastart commented on scr/PersonCreation.java
> +        String firstName;
te dwie zmienne mozesz zadeklorwac w linijkach 14 i 16(razem z inicjalizacja)

2020-05-12 18:19 UTC, pawelkoperjavastart commented on scr/PersonCreation.java
> +        int pesel;
te dwie zmienne mozesz zadeklorwac w linijkach 25i 27 (razem z inicjalizacja)

2020-05-16 17:08 UTC, CzarekOrlikowski commented on scr/PersonCreation.java
> +        String firstName;
OK

2020-05-16 17:09 UTC, CzarekOrlikowski commented on scr/PersonCreation.java
> +        int pesel;
OK

2020-05-16 17:10 UTC, merged